### ISSUE TITLE
duplicated stock quote

### ISSUE THREAD

**Issue by zhuqicn** [ted7726/FantasyStock#6]
![screen shot 2016-03-15 at 9 53 09 pm](https://cloud.githubusercontent.com/assets/6313395/13802404/a5efa8ce-eaf8-11e5-996f-b65607d15028.png)

**Comment by zhuqicn** [comment]
Fixed in [327d7bd](https://github.com/ted7726/FantasyStock/commit/327d7bd41df2d6872683884b68e8db0773eda17d)
![screen shot 2016-03-15 at 11 09 49 pm](https://cloud.githubusercontent.com/assets/6313395/13803653/9c7116ba-eb03-11e5-8f13-fc41b5b19db4.png)

**Comment by ted7726** [comment]
:+1:

**Comment by ted7726** [comment]
Fixed:
https://github.com/ted7726/FantasyStock/commit/480aec05cee635026e1c748c8e9dab35836c01e0
